name: i18n:extract,push,pull translations
# on:
#   push:
#     branches:
#       - main
on: [push]

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # extract
      - name: extract_messages
        run: |
          python setup.py extract_messages
      
      # # push
      # - name: extract_messages
      #   run: |
      #     python setup.py extract_messages

      # # pull all lang
      # - name: extract_messages
      #   run: |
      #     python setup.py extract_messages

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: i18n:extract,push,pull translations
          title: i18n:extract,push,pull translations
          body: i18n:extract,push,pull translations
          branch: translations  # name of branch which PR is created from

